# Generated by Django 3.0.5 on 2020-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_items_work_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
