# Generated by Django 3.0.5 on 2020-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
