# Generated by Django 3.0.5 on 2020-05-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='work_sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='work_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shop_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock', models.SmallIntegerField(default=0)),
                ('edition_count', models.SmallIntegerField(default=0)),
                ('frame', models.CharField(blank=True, choices=[('FR', 'Frame'), ('NF', 'No Frame')], max_length=2, null=True)),
                ('signed', models.BooleanField(default=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('personal_message', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.materials')),
                ('work_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.work_sizes')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.work_types')),
            ],
        ),
    ]
