# Generated by Django 3.0.5 on 2020-04-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_remove_work_items_shop_work'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_items',
            name='work_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_items'),
        ),
    ]
