# Generated by Django 3.0.5 on 2020-05-29 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_items',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work_images'),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.materials'),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='work_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.work_sizes'),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.work_types'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='work_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_items'),
        ),
    ]
