# Generated by Django 3.0.5 on 2020-05-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_orders_shipping'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_items',
            name='personal_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop_items',
            name='standard_text',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text', models.CharField(blank=True, max_length=3000)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.orders')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
