# Generated by Django 3.0.5 on 2020-05-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200503_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.materials'),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='work_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.work_sizes'),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.work_types'),
        ),
    ]
