# Generated by Django 3.0.5 on 2020-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_items_work_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_items',
            name='frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='signed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop_items',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
    ]
