# Generated by Django 3.0.5 on 2020-05-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_images_sort_order'),
        ('shop', '0004_auto_20200505_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_items',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.work_images'),
        ),
    ]
