# Generated by Django 3.0.5 on 2020-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
