# Generated by Django 3.0.5 on 2020-05-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_info_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop_info',
            new_name='shop_message',
        ),
    ]
