# Generated by Django 3.0.5 on 2020-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200520_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_types',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
