# Generated by Django 3.0.5 on 2020-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200529_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_items',
            name='coupon',
        ),
    ]
