# Generated by Django 3.0.5 on 2020-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='images')),
                ('position', models.CharField(choices=[('HZ', 'Horizontal'), ('VT', 'Vertical')], default='VT', max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('under_title', models.CharField(blank=True, max_length=50)),
                ('free_text', models.CharField(blank=True, max_length=3000)),
                ('work_item', models.BooleanField(blank=True, default=True)),
                ('shop_item', models.BooleanField(blank=True, default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('EU', 'Euro'), ('US', 'Dollar')], default='EU', max_length=2)),
                ('stock', models.SmallIntegerField(blank=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('shipping_abroad', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('edition_count', models.SmallIntegerField(blank=True)),
                ('frame', models.BooleanField(blank=True, default=False)),
                ('signed', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
