# Generated by Django 3.0.5 on 2020-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_items',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
