# Generated by Django 3.0.5 on 2020-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='main_image',
            field=models.ImageField(upload_to='images/works/'),
        ),
    ]
