# Generated by Django 3.0.5 on 2020-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_items',
            name='collection',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
