# Generated by Django 3.0.5 on 2020-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200429_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_items',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
