# Generated by Django 3.0.5 on 2020-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200503_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='sort_order',
            field=models.SmallIntegerField(default=999),
        ),
    ]
