# Generated by Django 3.0.5 on 2020-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200418_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='work_types',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
