# Generated by Django 3.0.5 on 2020-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200418_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='stock',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
