# Generated by Django 3.0.5 on 2020-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20200418_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_items',
            name='currency',
        ),
        migrations.AlterField(
            model_name='work_items',
            name='edition_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_items',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
