# Generated by Django 3.0.5 on 2020-04-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20200418_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.materials'),
        ),
        migrations.AlterField(
            model_name='work_items',
            name='work_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_sizes'),
        ),
        migrations.AlterField(
            model_name='work_items',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_types'),
        ),
    ]
