# Generated by Django 3.0.5 on 2020-04-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20200418_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_items',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='edition_count',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='material',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='price',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='signed',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='work_size',
        ),
        migrations.RemoveField(
            model_name='work_items',
            name='work_type',
        ),
        migrations.DeleteModel(
            name='materials',
        ),
        migrations.DeleteModel(
            name='work_sizes',
        ),
        migrations.DeleteModel(
            name='work_types',
        ),
    ]
