# Generated by Django 3.0.5 on 2020-04-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('works', '0011_work_items_shop_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='shop_work',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop_items'),
        ),
    ]
