# Generated by Django 3.0.5 on 2020-04-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20200421_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_items',
            name='shop_work',
        ),
    ]
