# Generated by Django 3.0.5 on 2020-04-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_remove_work_items_shop_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_image', models.ImageField(upload_to='images')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('work_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_items')),
            ],
        ),
    ]
