# Generated by Django 3.0.5 on 2020-04-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_work_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_images',
            name='work_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work_items'),
        ),
    ]
