# Generated by Django 3.0.5 on 2020-04-23 20:48

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20200423_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_images',
            name='title',
        ),
        migrations.AlterField(
            model_name='work_images',
            name='work_image',
            field=models.ImageField(upload_to=works.models.work_upload_dir),
        ),
    ]
