# Generated by Django 3.0.5 on 2020-04-25 09:43

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20200423_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_items',
            name='main_image',
            field=models.ImageField(upload_to=works.models.work_upload_dir),
        ),
    ]
