# Generated by Django 3.0.5 on 2020-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_auto_20200425_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_images',
            name='work_image',
            field=models.ImageField(upload_to='images/works'),
        ),
        migrations.AlterField(
            model_name='work_items',
            name='main_image',
            field=models.ImageField(upload_to='images/works'),
        ),
    ]
