# Generated by Django 3.0.5 on 2020-04-25 10:44

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_auto_20200425_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_images',
            name='work_image',
            field=models.ImageField(upload_to=works.models.work_upload_dir),
        ),
        migrations.AlterField(
            model_name='work_items',
            name='main_image',
            field=models.ImageField(upload_to=works.models.work_upload_dir),
        ),
    ]
